#!/bin/bash

echo "🏇 TUNISIA JOCKEY CLUB - Commandes Utiles"
echo "========================================="
echo ""
echo "📋 COMMANDES DISPONIBLES:"
echo ""
echo "🚀 DÉVELOPPEMENT:"
echo "   npm run dev              # Lance frontend + backend"
echo "   npm install              # Installation dépendances"
echo ""
echo "🧪 TESTS:"
echo "   ./test-auth.sh           # Test authentification"
echo "   ./test-system.sh         # Test système complet"
echo "   ./debug-login-flow.sh    # Debug détaillé"
echo ""
echo "📊 SERVICES:"
echo "   docker-compose -f docker-compose.redis.yml up -d  # Démarrer Redis"
echo "   docker-compose down                               # Arrêter services"
echo "   ps aux | grep -E '(node|vite|nest)'              # Voir processus actifs"
echo ""
echo "🌐 URLS IMPORTANTES:"
echo "   Frontend:    http://localhost:5173"
echo "   Backend:     http://localhost:3000"
echo "   Dashboard:   http://localhost:5173/dashboard-main"
echo ""
echo "📁 STRUCTURE:"
echo "   ls -la frontend/app/routes/dashboard*             # Voir dashboards"
echo "   ls -la _archive/                                  # Voir fichiers archivés"
echo ""
echo "🎯 DÉMARRAGE RAPIDE:"
echo "   1. npm install"
echo "   2. npm run dev"
echo "   3. Ouvrir http://localhost:5173/dashboard-main"
